"""The phone link on the Spark (phone contract sections 4-6): sealed inbox entries, the gate, the phone key's
authorized_keys line and the relay helper. Invented content and throwaway keys only; nothing here reads or
writes the real ~/.ssh.

The sealed entries below are vectors of the phone's own sealing code (MindloomLink seal_vectors.json,
generated by an independent Python implementation): the Spark must hand back exactly these bytes under
exactly this id, because the id is part of what the Mac authenticates.
"""

from __future__ import annotations

import base64
import getpass
import json
import os
import shutil
import socket
import subprocess
import sys
import threading
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from conftest import TINY_PNG_B64
from organizer import api, inbox_cli, phone_keys, sealed
from organizer.clients import HashEmbedClient
from organizer.api import build_organizer, create_app
from organizer.inbox import InboxStore

SPARK = Path(__file__).resolve().parents[1]
RELAY_HELPER = SPARK / "relay-authorize"
WHEN = "2026-09-30T09:15:05+08:00"

# vector "text-keyboard" (the keyboard's dictation, sealed on the phone)
V_ID = "5b0d7c1e-2f4a-4c61-9d3e-8a7b6c5d4e3f"
V_WIRE = (
    "mlseal1.lt8AOLq8LiTTAAZMoj9bJkwwXOjvWNc3shai0Bjxr0Au3Kegnyx29RY45gabIQzXZKmabxfXKFS19TnJNEG8yZ7H3A-sBmaIzPHA"
    "phTpsbhZ7w0Xy87VFD9EKLNoqNjrkpTJFavKmJs-qoM3yI20tN8UctkUuyOvoczayLGsFuqoEItskrKIoJAoCZ9h7JOxcJ3ACQy53HnVq4ueW"
    "Iu32vSFWtEG1y104w_0npMPmwnRHW6uAw7vBL2qPF7u9NF9CMii_CjrN8mb7mgC5HfSjdoWfQI3XMMHqFEOx-GmxKAdnGmnXpz8Fp7HR9-RnI"
    "qI7rVVt7Q")
V_MAC_PRIV = "fc8c4db3f5658931d5c12cf4b2272d9c157ad3fa1d6b8d6e3f0739e91ceadace"
V_PLAINTEXT_PHRASE = "明天下午三点和王老师对一下实验方案"


def wire_of(n_bytes: int, fill: bytes = b"\x5a") -> str:
    """A sealed-shaped wire string of n sealed bytes (not a real seal: the Spark never opens one)."""
    return sealed.PREFIX + base64.urlsafe_b64encode(fill * n_bytes).decode().rstrip("=")


def sealed_body(entry_id: str = V_ID, wire: str = V_WIRE, **over) -> dict:
    body = {"inbox_id": entry_id, "source": "sealed", "kind": "sealed", "blob": wire, "received_at": WHEN}
    body.update(over)
    return body


def phone_reply(stdout: str) -> dict:
    """What the phone app reads: the last line of stdout that is a JSON object (InboxGateReply)."""
    for line in reversed(stdout.splitlines()):
        try:
            obj = json.loads(line.strip())
        except ValueError:
            continue
        if isinstance(obj, dict):
            return obj
    raise AssertionError(f"no JSON line in {stdout!r}")


def files_under(root: Path) -> list[Path]:
    return [p for p in root.rglob("*") if p.is_file()]


@pytest.fixture
def locked(settings, chat):
    """The service as deployed: the store starts locked (the phone must still be able to add)."""
    settings.unlock_key = None
    org = build_organizer(settings, chat=chat, embedder=HashEmbedClient())
    app = create_app(settings, organizer=org)
    with TestClient(app, headers={"Authorization": f"Bearer {app.state.link_token}"}) as c:
        yield c


# ---- the wire shape -------------------------------------------------------------------------------------


def test_wire_shape_limits_follow_the_phone():
    # 36,000,000 sealed bytes before base64url, the phone's MindloomSeal.maximumWireBytes
    assert sealed.MAX_WIRE_CHARS == 48_000_008
    assert sealed.wire_problem(V_WIRE) is None
    assert sealed.wire_problem(wire_of(sealed.MIN_SEALED_BYTES)) is None
    assert len(wire_of(sealed.MIN_SEALED_BYTES)) == sealed.MIN_WIRE_CHARS == 88
    assert sealed.wire_problem(wire_of(sealed.MIN_SEALED_BYTES - 1)) == "too_short"
    biggest = wire_of(sealed.MAX_SEALED_BYTES)
    assert len(biggest) == sealed.MAX_WIRE_CHARS and sealed.wire_problem(biggest) is None
    assert sealed.wire_problem(biggest + "A") == "too_large"
    assert sealed.wire_problem("mlseal2." + V_WIRE[8:]) == "not_sealed"
    assert sealed.wire_problem(V_WIRE[8:]) == "not_sealed"
    assert sealed.wire_problem(V_WIRE + "=") == "malformed"          # padding is not base64url_nopad
    assert sealed.wire_problem(V_WIRE[:-3] + "+/Q") == "malformed"   # the standard alphabet is not base64url
    assert sealed.wire_problem(V_WIRE[:-2] + "é") == "malformed"
    whole_groups = sealed.PREFIX + "A" * 400
    assert sealed.wire_problem(whole_groups) is None
    assert sealed.wire_problem(whole_groups + "A") == "malformed"  # unpadded base64 never ends in 1 character
    assert sealed.wire_problem(whole_groups + "AA") is None and sealed.wire_problem(whole_groups + "AAA") is None
    assert sealed.is_entry_id(V_ID) and not sealed.is_entry_id(V_ID.upper()) and not sealed.is_entry_id(V_ID[:-1])


# ---- sealed entries through the API ------------------------------------------------------------------------


def test_sealed_add_list_ack(client, settings):
    r = client.post("/v1/inbox", json=sealed_body())
    assert r.status_code == 200 and r.json() == {"ok": True, "id": V_ID, "inbox_id": V_ID, "duplicate": False}
    got = client.get("/v1/inbox", params={"since": 0}).json()
    assert got["pending"] == 1 and client.get("/v1/health").json()["inbox_pending"] == 1
    [entry] = got["items"]
    # the contract's shape: id, kind, blob, received_at (+ seq for the cursor); nothing else about the entry
    assert set(entry) == {"inbox_id", "kind", "blob", "received_at", "seq"}
    assert (entry["inbox_id"], entry["kind"], entry["blob"], entry["received_at"]) == (V_ID, "sealed", V_WIRE, WHEN)
    assert got["cursor"] == entry["seq"]
    row = client.app.state.organizer.inbox.one(V_ID)
    assert (row["source"], row["kind"], row["text"], row["image"]) == ("sealed", "sealed", None, None)
    # the phone's words never reach the Spark; only the sealed string does
    for p in files_under(settings.data_dir):
        assert V_PLAINTEXT_PHRASE.encode() not in p.read_bytes(), p.name
    # ack deletes the blob (secure_delete: overwritten in the file) and keeps a content-free row
    assert client.post(f"/v1/inbox/{V_ID}/ack").json() == {"ok": True, "acked": True, "already": False}
    row = client.app.state.organizer.inbox.one(V_ID)
    assert (row["blob"], row["acked"]) == (None, 1)
    assert client.get("/v1/inbox", params={"since": 0}).json()["items"] == []
    for p in files_under(settings.data_dir):
        assert V_WIRE[8:60].encode() not in p.read_bytes(), p.name
    # nothing is organized on the Spark: an inbox entry is not an item
    assert client.get("/v1/health").json()["items"] == 0


def test_what_the_mac_gets_back_opens_with_the_id_it_was_sealed_under(client):
    """The Mac side of section 5, done here with the vector's Mac key: the stored blob and id are the phone's."""
    x25519 = pytest.importorskip("cryptography.hazmat.primitives.asymmetric.x25519")
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF

    client.post("/v1/inbox", json=sealed_body())
    entry = client.get("/v1/inbox").json()["items"][0]
    raw = base64.urlsafe_b64decode(entry["blob"][len(sealed.PREFIX):] + "=" * (-len(entry["blob"][8:]) % 4))
    mac = x25519.X25519PrivateKey.from_private_bytes(bytes.fromhex(V_MAC_PRIV))
    eph, nonce, box = raw[:32], raw[32:44], raw[44:]
    mac_pub = mac.public_key().public_bytes_raw()
    shared = mac.exchange(x25519.X25519PublicKey.from_public_bytes(eph))
    key = HKDF(hashes.SHA256(), 32, salt=eph + mac_pub, info=b"mindloom-inbox-seal-v1").derive(shared)
    plain = ChaCha20Poly1305(key).decrypt(nonce, box, ("mindloom-inbox-v1|" + entry["inbox_id"]).encode())
    payload = json.loads(plain)
    assert payload["kind"] == "text" and payload["source"] == "iPhone 键盘" and V_PLAINTEXT_PHRASE in payload["text"]
    with pytest.raises(Exception):  # an id changed in any way (for example upper-cased) no longer opens
        ChaCha20Poly1305(key).decrypt(nonce, box, ("mindloom-inbox-v1|" + entry["inbox_id"].upper()).encode())


def test_sealed_retry_is_a_duplicate_also_after_the_ack(client):
    assert client.post("/v1/inbox", json=sealed_body()).json()["duplicate"] is False
    again = client.post("/v1/inbox", json=sealed_body())
    assert again.status_code == 200 and again.json() == {"ok": True, "id": V_ID, "inbox_id": V_ID, "duplicate": True}
    client.post(f"/v1/inbox/{V_ID}/ack")
    assert client.post("/v1/inbox", json=sealed_body()).json()["duplicate"] is True
    assert client.get("/v1/inbox").json()["items"] == []  # the Mac already has it; it does not come back


def test_sealed_entries_refuse_anything_but_the_contract_shape(client):
    bad = [
        sealed_body(entry_id=V_ID.upper()),                 # the id is in the AAD: never normalized, refused
        sealed_body(entry_id=None),                         # a sealed entry cannot be opened without its id
        sealed_body(entry_id="5b0d7c1e2f4a4c619d3e8a7b6c5d4e3f0000"),
        sealed_body(wire="mlseal2." + V_WIRE[8:]),
        sealed_body(wire=V_WIRE + "="),
        sealed_body(wire=wire_of(sealed.MIN_SEALED_BYTES - 1)),
        sealed_body(wire=None),
        sealed_body(source="iPhone"),                       # no plaintext metadata next to a sealed blob
        sealed_body(text="明文"),
        sealed_body(image_b64=TINY_PNG_B64),
        {"source": "iPhone", "kind": "text", "text": "x", "blob": V_WIRE, "received_at": WHEN},
    ]
    for body in bad:
        r = client.post("/v1/inbox", json=body)
        assert r.status_code == 422, body
        # the refusal does not echo the entry back (no plaintext share, no 48 MB blob in an error)
        assert V_WIRE[8:40] not in r.text and "明文" not in r.text and len(r.text) < 1000
    assert client.get("/v1/inbox").json()["items"] == []
    # other routes keep FastAPI's usual validation answer
    other = client.get("/v1/debug/runs", params={"limit": 0})
    assert other.status_code == 422 and "input" in other.json()["detail"][0]


def test_the_largest_sealed_entry_is_accepted_and_one_more_character_is_not(client):
    biggest = wire_of(sealed.MAX_SEALED_BYTES, b"\x01")
    entry_id = "0f1e2d3c-4b5a-4968-8776-a5b4c3d2e1f0"
    r = client.post("/v1/inbox", json=sealed_body(entry_id, biggest))
    assert r.status_code == 200 and r.json()["id"] == entry_id
    assert client.get("/v1/inbox").json()["items"][0]["blob"] == biggest
    r = client.post("/v1/inbox", json=sealed_body("0f1e2d3c-4b5a-4968-8776-a5b4c3d2e1f1", biggest + "AA"))
    assert r.status_code == 422 and len(r.text) < 1000


def test_a_large_sealed_entry_comes_alone_in_its_page(client, monkeypatch):
    monkeypatch.setattr(api, "INBOX_PAGE_BYTES", 400)
    ids = ["11111111-2222-4333-8444-55555555555" + str(i) for i in range(3)]
    client.post("/v1/inbox", json=sealed_body(ids[0], wire_of(600)))
    client.post("/v1/inbox", json=sealed_body(ids[1], wire_of(100)))
    client.post("/v1/inbox", json=sealed_body(ids[2], wire_of(100)))
    first = client.get("/v1/inbox", params={"since": 0}).json()
    assert [i["inbox_id"] for i in first["items"]] == [ids[0]] and first["more"] is True
    second = client.get("/v1/inbox", params={"since": first["cursor"]}).json()
    assert [i["inbox_id"] for i in second["items"]] == ids[1:]


def test_a_page_reads_only_the_entries_it_returns(tmp_path):
    store = InboxStore(tmp_path / "inbox.db")
    ids = [f"22222222-3333-4444-8555-66666666666{i}" for i in range(4)]
    for i, n in zip(ids, (300, 300, 5000, 10)):
        store.add(sealed_body(i, wire_of(n)), None)
    statements: list[str] = []
    store.conn.set_trace_callback(statements.append)
    rows, more = store.page(0, 20, budget=1000)          # 408 + 408 chars fit, the 6,675-char one does not
    assert [r["inbox_id"] for r in rows] == ids[:2] and more is True
    content_reads = [q for q in statements if "SELECT inbox_id" in q]
    assert len(content_reads) == 1 and "seq <=" in content_reads[0]  # only the chosen range is read
    rows, more = store.page(rows[-1]["seq"], 20, budget=1000)
    assert [r["inbox_id"] for r in rows] == [ids[2]] and more is True  # alone, over the budget
    rows, more = store.page(rows[-1]["seq"], 20, budget=1000)
    assert [r["inbox_id"] for r in rows] == [ids[3]] and more is False
    assert store.page(rows[-1]["seq"], 20, budget=1000) == ([], False)
    assert store.page(0, 2, budget=10 ** 9)[1] is True     # a full page may have more behind it
    store.close()


def test_sealed_add_works_while_the_store_is_locked_and_wipe_drops_it(locked, settings):
    c = locked
    assert c.get("/v1/health").json()["locked"] is True
    r = c.post("/v1/inbox", json=sealed_body())
    assert r.status_code == 200 and c.get("/v1/health").json()["inbox_pending"] == 1
    assert c.post("/v1/wipe", json={"key_id": "0000000000000000"}).json() == {"wiped": True}
    assert c.get("/v1/health").json()["inbox_pending"] == 0
    assert c.app.state.organizer.inbox.one(V_ID)["blob"] is None
    for p in files_under(settings.data_dir):
        assert V_WIRE[8:60].encode() not in p.read_bytes(), p.name


def test_an_older_inbox_db_gets_the_blob_column_and_keeps_its_entries(tmp_path):
    from organizer import db

    path = tmp_path / "inbox.db"
    conn = db.connect(str(path), None, isolation_level=None)
    conn.execute("CREATE TABLE inbox(inbox_id TEXT PRIMARY KEY, source TEXT NOT NULL, kind TEXT NOT NULL,"
                 " text TEXT, image BLOB, received_at TEXT NOT NULL, created_at TEXT NOT NULL,"
                 " acked INTEGER NOT NULL DEFAULT 0, acked_at TEXT, seq INTEGER NOT NULL)")
    conn.execute("CREATE TABLE meta(key TEXT PRIMARY KEY, value TEXT NOT NULL)")
    conn.execute("INSERT INTO meta VALUES ('seq', '5')")
    conn.execute("INSERT INTO inbox VALUES ('1b4e28ba-2fa1-11d2-883f-0016d3cca427', 'iPhone', 'text', '旧的一条',"
                 " NULL, ?, ?, 0, NULL, 5)", (WHEN, WHEN))
    conn.close()
    store = InboxStore(path)
    assert [r["text"] for r in store.since(0, 10)] == ["旧的一条"]
    store.add(sealed_body(), None)
    assert [r["kind"] for r in store.since(0, 10)] == ["text", "sealed"]
    assert store.one(V_ID)["blob"] == V_WIRE
    store.close()


# ---- the zhiji-inbox command ------------------------------------------------------------------------------


def test_cli_sealed_add_prints_what_the_phone_expects(client, capsys):
    # the phone's command, with the wire on stdin (a trailing newline is tolerated)
    assert inbox_cli.main(["add", "--sealed", "--id", V_ID, "--json"], stdin=(V_WIRE + "\n").encode(),
                          client=client) == 0
    reply = phone_reply(capsys.readouterr().out)
    assert reply == {"ok": True, "id": V_ID, "inbox_id": V_ID, "duplicate": False}
    assert client.get("/v1/inbox").json()["items"][0]["blob"] == V_WIRE
    # a retry after a lost reply is a success, marked duplicate
    assert inbox_cli.main(["add", "--sealed", "--id", V_ID, "--json"], stdin=V_WIRE.encode(), client=client) == 0
    assert phone_reply(capsys.readouterr().out)["duplicate"] is True
    # without --json: one plain line
    other = "0f1e2d3c-4b5a-4968-8776-a5b4c3d2e1f0"
    assert inbox_cli.main(["add", "--sealed", "--id", other], stdin=wire_of(200).encode(), client=client) == 0
    assert "已收进织机" in capsys.readouterr().out
    assert inbox_cli.main(["status"], client=client) == 0
    assert "2 条" in capsys.readouterr().out


def test_cli_sealed_refusals_answer_in_json_and_send_nothing(client, capsys):
    cases = [
        (["add", "--sealed", "--json"], V_WIRE, "bad_id"),
        (["add", "--sealed", "--id", V_ID.upper(), "--json"], V_WIRE, "bad_id"),
        (["add", "--sealed", "--id", V_ID, "--source", "iPhone", "--json"], V_WIRE, "bad_args"),
        (["add", "--sealed", "--id", V_ID, "--image", "-", "--json"], V_WIRE, "bad_args"),
        (["add", "--sealed", "--id", V_ID, "--json"], "明文不是封好的", "malformed"),
        (["add", "--sealed", "--id", V_ID, "--json"], "hello", "not_sealed"),
        (["add", "--sealed", "--id", V_ID, "--json"], V_WIRE + "=", "malformed"),
        (["add", "--sealed", "--id", V_ID, "--json"], "", "not_sealed"),
    ]
    for argv, stdin, code in cases:
        assert inbox_cli.main(argv, stdin=stdin.encode(), client=client) == 1, argv
        assert phone_reply(capsys.readouterr().out) == {"ok": False, "error": code}, argv
    # more than the largest wire: refused after reading one byte past the limit, before anything is sent
    too_big = (sealed.PREFIX + "A" * (inbox_cli.MAX_SEALED_STDIN)).encode()
    assert inbox_cli.main(["add", "--sealed", "--id", V_ID, "--json"], stdin=too_big, client=client) == 1
    assert phone_reply(capsys.readouterr().out) == {"ok": False, "error": "too_large"}
    assert client.get("/v1/inbox").json()["items"] == []


def test_cli_accepts_the_largest_wire_on_stdin(client, capsys):
    biggest = wire_of(sealed.MAX_SEALED_BYTES, b"\x07")
    assert inbox_cli.main(["add", "--sealed", "--id", V_ID, "--json"], stdin=(biggest + "\r\n").encode(),
                          client=client) == 0
    assert phone_reply(capsys.readouterr().out)["ok"] is True
    assert client.get("/v1/inbox").json()["items"][0]["blob"] == biggest


def test_cli_without_a_running_organizer_answers_unavailable(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("ORGANIZER_DATA_DIR", str(tmp_path))
    monkeypatch.delenv("ORGANIZER_UDS", raising=False)
    assert inbox_cli.main(["add", "--sealed", "--id", V_ID, "--json"], stdin=V_WIRE.encode()) == 2
    assert phone_reply(capsys.readouterr().out) == {"ok": False, "error": "unavailable"}


def test_plaintext_adds_are_refused_and_nothing_is_sent(client, capsys):
    """The iOS Shortcut path is retired: it cannot seal, so its shares would wait here in plaintext (review F9).
    A plaintext add is refused before the organizer is contacted; the API refuses one too, without echoing it."""
    sent = []
    client.app.state.organizer.inbox.add = lambda *a, **k: sent.append(a)  # would be called on a store
    for argv, stdin in ((["add", "--json"], "快捷指令分享的一段".encode()),
                        (["add", "--source", "iPhone", "--json"], b"x"),
                        (["add", "--id", "1b4e28ba-2fa1-11d2-883f-0016d3cca427", "--json"], b"x"),
                        (["add", "--image", "-", "--json"], base64.b64encode(base64.b64decode(TINY_PNG_B64))),
                        (["add", "--text", "hi", "--json"], b"")):
        assert inbox_cli.main(argv, stdin=stdin, client=client) == 1
        assert phone_reply(capsys.readouterr().out) == {"ok": False, "error": "not_sealed"}
    for body in ({"source": "iPhone", "kind": "text", "text": "快捷指令分享的一段", "received_at": WHEN},
                 {"source": "iPhone", "kind": "image", "image_b64": TINY_PNG_B64, "received_at": WHEN},
                 {"inbox_id": V_ID, "source": "sealed", "kind": "text", "text": "x", "received_at": WHEN}):
        r = client.post("/v1/inbox", json=body)
        assert r.status_code == 422 and "快捷指令" not in r.text and TINY_PNG_B64 not in r.text
    assert sent == []


def test_gate_allows_the_sealed_add_and_status_only():
    ok = inbox_cli.gate_argv
    assert ok(f"zhiji-inbox add --sealed --id {V_ID} --json") == ["add", "--sealed", "--id", V_ID, "--json"]
    assert ok(f"/home/u/spark/zhiji-inbox add --sealed --id {V_ID}") is not None
    assert ok(f"zhiji-inbox add --json --id {V_ID} --sealed") == ["add", "--json", "--id", V_ID, "--sealed"]
    assert ok("zhiji-inbox status") == ["status"]
    refused = [
        "zhiji-inbox authorize-phone --key-id p1 --pubkey x", "zhiji-inbox revoke-phone --key-id p1",
        "zhiji-inbox list-phones", "zhiji-inbox list-phones --json", "authorize-phone --key-id p1 --pubkey -",
        f"zhiji-inbox add --sealed --id {V_ID} authorize-phone", "zhiji-inbox add --sealed --id",
        "zhiji-inbox add --sealed --id not-a-uuid", f"zhiji-inbox add --sealed --id={V_ID}",
        f"zhiji-inbox add --sealed --id {V_ID}; zhiji-inbox list-phones", "zhiji-inbox status --json",
        "zhiji-inbox gate", "zhiji-inbox add --text hi", "zhiji-inbox add --image /etc/passwd",
        f"zhiji-inbox add --sealed --id '{V_ID} x'", "zhiji-inbox add --sealed --id $(id)",
        # the retired plaintext path: an add must be sealed and carry its id; no source, image or text
        "zhiji-inbox add", "zhiji-inbox add --json", "zhiji-inbox add --source iPhone",
        f"zhiji-inbox add --id {V_ID} --json", "zhiji-inbox add --sealed --json",
        f"zhiji-inbox add --id {V_ID.upper()} --source iPhone --image - --json",
        f"zhiji-inbox add --sealed --id {V_ID} --source iPhone", f"zhiji-inbox add --sealed --id {V_ID} --image -",
        f"zhiji-inbox add --sealed --sealed --id {V_ID}", f"zhiji-inbox add --sealed --id {V_ID} --id {V_ID}",
    ]
    for cmd in refused:
        assert ok(cmd) is None, cmd


def test_gate_runs_a_sealed_add_and_refuses_admin_commands(client, monkeypatch, capsys, tmp_path):
    monkeypatch.setenv("SSH_ORIGINAL_COMMAND", f"zhiji-inbox add --sealed --id {V_ID} --json")
    assert inbox_cli.main(["gate"], stdin=V_WIRE.encode(), client=client) == 0
    assert phone_reply(capsys.readouterr().out) == {"ok": True, "id": V_ID, "inbox_id": V_ID, "duplicate": False}
    # an admin command through the gate never reaches authorized_keys
    monkeypatch.setenv("HOME", str(tmp_path))
    pub = f"ssh-ed25519 {base64.b64encode(ed25519_blob(b'z' * 32)).decode()}"
    for cmd in (f"zhiji-inbox authorize-phone --key-id p1 --pubkey '{pub}' --json", "zhiji-inbox list-phones --json",
                "zhiji-inbox revoke-phone --key-id p1 --json"):
        monkeypatch.setenv("SSH_ORIGINAL_COMMAND", cmd)
        assert inbox_cli.main(["gate"], stdin=b"", client=client) == 1
        assert phone_reply(capsys.readouterr().out) == {"ok": False, "error": "not_allowed"}
    assert not (tmp_path / ".ssh").exists()


# ---- the phone key's authorized_keys line (authorize-phone / revoke-phone / list-phones) -----------------


def ed25519_blob(raw32: bytes) -> bytes:
    name = b"ssh-ed25519"
    return len(name).to_bytes(4, "big") + name + (32).to_bytes(4, "big") + raw32


def pubkey(seed: int, comment: str = "") -> str:
    b64 = base64.b64encode(ed25519_blob(bytes([seed]) * 32)).decode()
    return f"ssh-ed25519 {b64}" + (f" {comment}" if comment else "")


@pytest.fixture
def gate_program(tmp_path) -> str:
    p = tmp_path / "bin" / "zhiji-inbox"
    p.parent.mkdir()
    p.write_text("#!/bin/sh\nexit 0\n")
    p.chmod(0o755)
    return str(p)


# Lines that are not ours, in every shape an authorized_keys file may hold them (the last one without a
# final newline). They must survive every change byte for byte.
FOREIGN = (b"# my laptop\n"
           b"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFOREIGNFOREIGNFOREIGNFOREIGNFOREIGNFOREIGN1 me@laptop\n"
           b"\n"
           b'command="/usr/bin/backup --dir \\"a b\\"",no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC7 backup\r\n'
           b"# old phone mindloom-phone:p1\n"
           b"from=\"*.example\" ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAI tablet")


def test_authorize_appends_one_restricted_line_and_leaves_every_other_line(tmp_path, gate_program):
    ak = tmp_path / "authorized_keys"
    ak.write_bytes(FOREIGN)
    ak.chmod(0o644)
    out = phone_keys.authorize("p1", pubkey(1, "mindloom-phone:p1"), path=ak, gate_path=gate_program)
    assert out["changed"] is True and out["replaced"] is False and out["fingerprint"].startswith("SHA256:")
    b64 = pubkey(1).split()[1]
    expected = f'command="{gate_program} gate",restrict ssh-ed25519 {b64} mindloom-phone:p1'.encode()
    assert ak.read_bytes() == FOREIGN + b"\n" + expected + b"\n"   # only a final newline was added
    assert oct(ak.stat().st_mode & 0o777) == "0o600"
    # idempotent: the same call again does not even rewrite the file
    inode, mtime = ak.stat().st_ino, ak.stat().st_mtime_ns
    assert phone_keys.authorize("p1", pubkey(1), path=ak, gate_path=gate_program)["changed"] is False
    assert (ak.stat().st_ino, ak.stat().st_mtime_ns) == (inode, mtime)
    # a second phone is a second line
    phone_keys.authorize("p2", pubkey(2), path=ak, gate_path=gate_program)
    listed = phone_keys.list_phones(path=ak)["phones"]
    assert [(p["key_id"], p["gate"], p["restricted"]) for p in listed] == [("p1", gate_program, True),
                                                                            ("p2", gate_program, True)]
    # the comment line that merely mentions a marker is not a phone
    assert ak.read_bytes().startswith(FOREIGN)


def test_pairing_again_replaces_the_line_in_place(tmp_path, gate_program):
    ak = tmp_path / "authorized_keys"
    ak.write_bytes(FOREIGN + b"\n")
    phone_keys.authorize("p1", pubkey(1), path=ak, gate_path=gate_program)
    phone_keys.authorize("p2", pubkey(2), path=ak, gate_path=gate_program)
    out = phone_keys.authorize("p1", pubkey(3), path=ak, gate_path=gate_program)
    assert out["changed"] is True and out["replaced"] is True
    lines = ak.read_bytes().split(b"\n")
    assert pubkey(3).split()[1].encode() in lines[-3] and lines[-3].endswith(b"mindloom-phone:p1")
    assert lines[-2].endswith(b"mindloom-phone:p2") and lines[-1] == b""
    assert pubkey(1).split()[1].encode() not in ak.read_bytes()
    assert ak.read_bytes().startswith(FOREIGN + b"\n")


def test_a_key_already_on_another_line_is_refused(tmp_path, gate_program):
    ak = tmp_path / "authorized_keys"
    ak.write_bytes(FOREIGN + b"\n" + pubkey(5, "someone@else").encode() + b"\n")
    before = ak.read_bytes()
    with pytest.raises(phone_keys.Refused) as e:
        phone_keys.authorize("p1", pubkey(5), path=ak, gate_path=gate_program)
    assert e.value.code == "key_in_use" and ak.read_bytes() == before
    phone_keys.authorize("p1", pubkey(6), path=ak, gate_path=gate_program)
    with pytest.raises(phone_keys.Refused):  # one key, one phone id
        phone_keys.authorize("p2", pubkey(6), path=ak, gate_path=gate_program)


def test_revoke_removes_only_that_phone_and_is_idempotent(tmp_path, gate_program):
    ak = tmp_path / "authorized_keys"
    ak.write_bytes(FOREIGN + b"\n")
    phone_keys.authorize("p1", pubkey(1), path=ak, gate_path=gate_program)
    phone_keys.authorize("p1.b", pubkey(2), path=ak, gate_path=gate_program)
    assert phone_keys.revoke("p1", path=ak) == {"ok": True, "key_id": "p1", "removed": 1}
    assert [p["key_id"] for p in phone_keys.list_phones(path=ak)["phones"]] == ["p1.b"]
    assert phone_keys.revoke("p1.b", path=ak)["removed"] == 1
    assert ak.read_bytes() == FOREIGN + b"\n"
    inode = ak.stat().st_ino
    assert phone_keys.revoke("p1", path=ak)["removed"] == 0 and ak.stat().st_ino == inode


def test_key_id_key_text_and_gate_path_are_validated(tmp_path, gate_program):
    ak = tmp_path / "authorized_keys"
    for key_id in ("", "-p", ".p", "a" * 65, "p 1", 'p"1', "p\n1", "p/1", "手机", "p:1", "p,1"):
        with pytest.raises(phone_keys.Refused) as e:
            phone_keys.authorize(key_id, pubkey(1), path=ak, gate_path=gate_program)
        assert e.value.code == "bad_key_id", key_id
        with pytest.raises(phone_keys.Refused):
            phone_keys.revoke(key_id, path=ak)
    b64 = pubkey(1).split()[1]
    rsa_like = base64.b64encode(b"\x00\x00\x00\x07ssh-rsa" + b"\x01" * 40).decode()
    short = base64.b64encode(ed25519_blob(b"\x01" * 32)[:-1]).decode()
    for text in ("", "ssh-ed25519", f"ssh-rsa {b64}", f"ssh-ed25519 {rsa_like}", f"ssh-ed25519 {short}",
                 f"ssh-ed25519 {b64}==", f"ssh-ed25519 {b64[:-1]}", f"ssh-ed25519 {b64} two words",
                 f'ssh-ed25519 {b64} "quoted"', f"ssh-ed25519 {b64} x\ncommand=\"sh\" ssh-ed25519 {b64}",
                 f'command="sh" ssh-ed25519 {b64}', f"ssh-ed25519 {b64}\r\nssh-ed25519 {b64}"):
        with pytest.raises(phone_keys.Refused) as e:
            phone_keys.authorize("p1", text, path=ak, gate_path=gate_program)
        assert e.value.code == "bad_pubkey", text
    for gate in ("zhiji-inbox", "./zhiji-inbox", "/tmp/a b/zhiji-inbox", '/tmp/a"b', "/tmp/../x",
                 str(tmp_path / "missing" / "zhiji-inbox"), "/x//y"):
        with pytest.raises(phone_keys.Refused) as e:
            phone_keys.authorize("p1", pubkey(1), path=ak, gate_path=gate)
        assert e.value.code == "bad_gate_path", gate
    assert not ak.exists()


def test_a_missing_ssh_dir_is_created_private_and_a_symlink_is_kept(tmp_path, gate_program):
    ak = tmp_path / "home" / ".ssh" / "authorized_keys"
    phone_keys.authorize("p1", pubkey(1), path=ak, gate_path=gate_program)
    assert oct(ak.parent.stat().st_mode & 0o777) == "0o700" and oct(ak.stat().st_mode & 0o777) == "0o600"
    real = tmp_path / "keys" / "ak"
    real.parent.mkdir()
    real.write_bytes(FOREIGN + b"\n")
    link = tmp_path / "link" / "authorized_keys"
    link.parent.mkdir()
    link.symlink_to(real)
    phone_keys.authorize("p1", pubkey(1), path=link, gate_path=gate_program)
    assert link.is_symlink() and real.read_bytes().startswith(FOREIGN + b"\n")
    assert real.read_bytes().rstrip().endswith(b"mindloom-phone:p1")


def test_concurrent_authorizations_all_land(tmp_path, gate_program):
    ak = tmp_path / "authorized_keys"
    ak.write_bytes(FOREIGN + b"\n")
    errors: list[BaseException] = []

    def one(i: int) -> None:
        try:
            phone_keys.authorize(f"p{i}", pubkey(10 + i), path=ak, gate_path=gate_program)
        except BaseException as exc:  # noqa: BLE001 (collected and asserted below)
            errors.append(exc)

    threads = [threading.Thread(target=one, args=(i,)) for i in range(12)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert not errors
    assert sorted(p["key_id"] for p in phone_keys.list_phones(path=ak)["phones"]) == sorted(f"p{i}" for i in range(12))
    assert ak.read_bytes().startswith(FOREIGN + b"\n")


def test_list_fingerprint_matches_ssh_keygen(tmp_path, gate_program):
    keygen = shutil.which("ssh-keygen")
    if keygen is None:
        pytest.skip("ssh-keygen not installed")
    subprocess.run([keygen, "-q", "-t", "ed25519", "-N", "", "-C", "x", "-f", str(tmp_path / "k")], check=True)
    pub = (tmp_path / "k.pub").read_text()
    ak = tmp_path / "authorized_keys"
    phone_keys.authorize("p1", pub, path=ak, gate_path=gate_program)
    want = subprocess.run([keygen, "-l", "-E", "sha256", "-f", str(tmp_path / "k.pub")], capture_output=True,
                          text=True, check=True).stdout.split()[1]
    assert phone_keys.list_phones(path=ak)["phones"][0]["fingerprint"] == want


def test_admin_commands_on_the_command_line(tmp_path, monkeypatch, capsys, gate_program):
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setenv("ZHIJI_INBOX_GATE", gate_program)
    assert inbox_cli.main(["authorize-phone", "--key-id", "p1", "--pubkey", pubkey(1)]) == 0
    assert json.loads(capsys.readouterr().out)["changed"] is True
    # the key on stdin (--pubkey -) avoids quoting it through a remote shell
    assert inbox_cli.main(["authorize-phone", "--key-id", "p2", "--pubkey", "-"], stdin=(pubkey(2) + "\n").encode()) == 0
    capsys.readouterr()
    assert inbox_cli.main(["list-phones", "--json"]) == 0
    assert [p["key_id"] for p in json.loads(capsys.readouterr().out)["phones"]] == ["p1", "p2"]
    line = (tmp_path / ".ssh" / "authorized_keys").read_text().splitlines()[0]
    assert line.startswith(f'command="{gate_program} gate",restrict ssh-ed25519 ')
    assert inbox_cli.main(["authorize-phone", "--key-id", "bad id", "--pubkey", pubkey(3)]) == 1
    assert json.loads(capsys.readouterr().out) == {"ok": False, "error": "bad_key_id"}
    assert inbox_cli.main(["revoke-phone", "--key-id", "p1"]) == 0
    assert json.loads(capsys.readouterr().out)["removed"] == 1
    # without ZHIJI_INBOX_GATE the gate is this checkout's own zhiji-inbox
    monkeypatch.delenv("ZHIJI_INBOX_GATE")
    assert phone_keys.default_gate_path() == str(SPARK / "zhiji-inbox")


def test_the_wrapper_names_itself_as_the_gate_and_an_instance_wrapper_keeps_its_own(tmp_path):
    env = {"PATH": os.environ.get("PATH", ""), "HOME": str(tmp_path), "ORGANIZER_VENV": sys.prefix,
           "ORGANIZER_DATA_DIR": str(tmp_path / "data")}
    pub = pubkey(1)
    r = subprocess.run([str(SPARK / "zhiji-inbox"), "authorize-phone", "--key-id", "p1", "--pubkey", pub],
                       env=env, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    line = (tmp_path / ".ssh" / "authorized_keys").read_text()
    assert line.startswith(f'command="{SPARK / "zhiji-inbox"} gate",restrict ')
    # ctl.sh gate-wrapper writes an instance wrapper that pairs phones under its own path
    wrapper = tmp_path / "inst" / "bin" / "zhiji-inbox"
    r = subprocess.run(["bash", str(SPARK / "ctl.sh"), "gate-wrapper", str(wrapper)], capture_output=True, text=True,
                       env={**env, "ORGANIZER_RUN_DIR": str(tmp_path / "run"), "ORGANIZER_LOG_DIR": str(tmp_path / "logs")})
    assert r.returncode == 0 and wrapper.exists(), r.stdout + r.stderr
    r = subprocess.run([str(wrapper), "authorize-phone", "--key-id", "p1", "--pubkey", pub],
                       env={"PATH": env["PATH"], "HOME": str(tmp_path)}, capture_output=True, text=True)
    assert r.returncode == 0 and json.loads(r.stdout)["replaced"] is True, r.stderr
    assert (tmp_path / ".ssh" / "authorized_keys").read_text().startswith(f'command="{wrapper} gate",restrict ')
    for bad in ("relative/zhiji-inbox", str(tmp_path / "inst" / "bin" / "inbox-gate"), str(tmp_path / "a b" / "zhiji-inbox")):
        r = subprocess.run(["bash", str(SPARK / "ctl.sh"), "gate-wrapper", bad], capture_output=True, text=True,
                           env={**env, "ORGANIZER_RUN_DIR": str(tmp_path / "run"), "ORGANIZER_LOG_DIR": str(tmp_path / "logs")})
        assert r.returncode == 2, bad


# ---- the relay helper (POSIX sh, piped to the relay over SSH) --------------------------------------------


def shells() -> list[str]:
    found = []
    for name in ("sh", "dash", "bash"):
        path = shutil.which(name)
        if path and os.path.realpath(path) not in {os.path.realpath(f) for f in found}:
            found.append(path)
    return found


def relay(home: Path, *args: str, shell: str = "sh") -> tuple[int, dict, str]:
    """Run the helper exactly as the Mac does: the script on stdin (`sh -s -- …`), arguments as plain words."""
    r = subprocess.run([shell, "-s", "--", *args], input=RELAY_HELPER.read_bytes(), capture_output=True,
                       env={"PATH": os.environ.get("PATH", "/usr/bin:/bin"), "HOME": str(home)}, timeout=30)
    return r.returncode, json.loads(r.stdout.decode().strip().splitlines()[-1]), r.stderr.decode()


@pytest.mark.parametrize("shell", shells(), ids=os.path.basename)
def test_relay_helper_adds_replaces_removes_and_lists(tmp_path, shell):
    home = tmp_path / "home"
    (home / ".ssh").mkdir(parents=True)
    ak = home / ".ssh" / "authorized_keys"
    ak.write_bytes(FOREIGN)
    b64 = pubkey(1).split()[1]
    rc, out, _ = relay(home, "add", "p1", "spark.example", "22", "ssh-ed25519", b64, shell=shell)
    assert rc == 0 and out == {"ok": True, "key_id": "p1", "changed": True, "replaced": False}
    line = (f'restrict,port-forwarding,permitopen="spark.example:22",permitlisten="127.0.0.1:1",command="false" '
            f"ssh-ed25519 {b64} mindloom-phone:p1").encode()
    assert ak.read_bytes() == FOREIGN + b"\n" + line + b"\n"
    assert oct(ak.stat().st_mode & 0o777) == "0o600"
    inode = ak.stat().st_ino
    rc, out, _ = relay(home, "add", "p1", "spark.example", "22", "ssh-ed25519", b64, shell=shell)
    assert rc == 0 and out["changed"] is False and ak.stat().st_ino == inode
    # a new target or key for the same phone replaces its line in place
    rc, out, _ = relay(home, "add", "p1", "spark.example", "2222", "ssh-ed25519", b64, shell=shell)
    assert rc == 0 and out["replaced"] is True
    b64b = pubkey(2).split()[1]
    relay(home, "add", "p2", "fd00::5", "22", "ssh-ed25519", b64b, shell=shell)
    text = ak.read_bytes()
    assert text.startswith(FOREIGN + b"\n") and b'permitopen="spark.example:2222"' in text
    assert b'permitopen="[fd00::5]:22"' in text
    assert [ln for ln in text.split(b"\n") if ln.endswith(b"mindloom-phone:p1") and not ln.startswith(b"#")] == [
        b'restrict,port-forwarding,permitopen="spark.example:2222",permitlisten="127.0.0.1:1",command="false" '
        + f"ssh-ed25519 {b64} mindloom-phone:p1".encode()]
    rc, out, _ = relay(home, "list", shell=shell)
    assert out == {"ok": True, "phones": ["p1", "p2"]}
    # the same key for another phone id would bypass nothing, but it is refused all the same
    rc, out, _ = relay(home, "add", "p3", "spark.example", "22", "ssh-ed25519", b64, shell=shell)
    assert rc == 1 and out["error"] == "key_in_use"
    for key_id, n in (("p1", 1), ("p1", 0), ("p2", 1)):
        rc, out, _ = relay(home, "remove", key_id, shell=shell)
        assert rc == 0 and out == {"ok": True, "key_id": key_id, "removed": n}
    assert ak.read_bytes() == FOREIGN + b"\n"
    assert sorted(p.name for p in (home / ".ssh").iterdir()) == ["authorized_keys"]  # no lock or temp left


@pytest.mark.parametrize("shell", shells(), ids=os.path.basename)
def test_relay_helper_refuses_bad_input_and_creates_what_is_missing(tmp_path, shell):
    home = tmp_path / "home"
    home.mkdir()
    b64 = pubkey(1).split()[1]
    bad = [
        (("add", "-p", "h", "22", "ssh-ed25519", b64), "bad_key_id"),
        (("add", "p 1", "h", "22", "ssh-ed25519", b64), "bad_key_id"),
        (("add", "a" * 65, "h", "22", "ssh-ed25519", b64), "bad_key_id"),
        (("add", "p1", "h;id", "22", "ssh-ed25519", b64), "bad_host"),
        (("add", "p1", 'h"', "22", "ssh-ed25519", b64), "bad_host"),
        (("add", "p1", "-oProxyCommand=x", "22", "ssh-ed25519", b64), "bad_host"),
        (("add", "p1", "h", "0", "ssh-ed25519", b64), "bad_port"),
        (("add", "p1", "h", "65536", "ssh-ed25519", b64), "bad_port"),
        (("add", "p1", "h", "22x", "ssh-ed25519", b64), "bad_port"),
        (("add", "p1", "h", "22", "ssh-rsa", b64), "bad_pubkey"),
        (("add", "p1", "h", "22", "ssh-ed25519", b64 + "A"), "bad_pubkey"),
        (("add", "p1", "h", "22", "ssh-ed25519", b64[:-1] + '"'), "bad_pubkey"),
        (("add", "p1", "h", "22", "ssh-ed25519", "AAAAB3NzaC1yc2E" + b64[15:]), "bad_pubkey"),
        (("add", "p1", "h", "22", "ssh-ed25519"), "bad_args"),
        (("remove",), "bad_args"),
        (("delete", "p1"), "bad_args"),
    ]
    for args, code in bad:
        rc, out, _ = relay(home, *args, shell=shell)
        assert rc == 1 and out == {"ok": False, "error": code}, args
    # ~/.ssh and authorized_keys are created private when missing
    rc, out, _ = relay(home, "add", "p1", "spark.example", "22", "ssh-ed25519", b64, shell=shell)
    assert rc == 0
    assert oct((home / ".ssh").stat().st_mode & 0o777) == "0o700"
    assert oct((home / ".ssh" / "authorized_keys").stat().st_mode & 0o777) == "0o600"


# ---- the real thing: OpenSSH's sshd enforcing both lines ----------------------------------------------------


def free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class SSHD:
    """A throwaway sshd on 127.0.0.1 run as this user, reading keys only from `authorized_keys`."""

    def __init__(self, root: Path, name: str, authorized_keys: Path):
        self.port = free_port()
        self.root = root
        hostkey = root / f"{name}_hostkey"
        subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-f", str(hostkey)], check=True)
        self.host_key = (root / f"{name}_hostkey.pub").read_text().split()[:2]
        config = root / f"{name}_sshd_config"
        config.write_text("\n".join([
            f"Port {self.port}", "ListenAddress 127.0.0.1", f"HostKey {hostkey}",
            f"AuthorizedKeysFile {authorized_keys}", f"PidFile {root / (name + '.pid')}", "UsePAM no",
            "StrictModes no", "PasswordAuthentication no", "KbdInteractiveAuthentication no",
            "PermitUserEnvironment no", "AllowTcpForwarding yes", "LogLevel VERBOSE", ""]))
        self.log = root / f"{name}.log"
        self.proc = subprocess.Popen([sshd_binary(), "-D", "-f", str(config),
                                      "-E", str(self.log)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        for _ in range(100):
            with socket.socket() as s:
                if s.connect_ex(("127.0.0.1", self.port)) == 0:
                    return
            if self.proc.poll() is not None:
                break
            time.sleep(0.05)
        self.stop()
        pytest.skip("sshd would not start as this user: " + (self.log.read_text()[-300:] if self.log.exists() else ""))

    def known_hosts_line(self) -> str:
        return f"[127.0.0.1]:{self.port} {' '.join(self.host_key)}\n"

    def stop(self) -> None:
        if self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()


def sshd_binary() -> str | None:
    return shutil.which("sshd") or next((p for p in ("/usr/sbin/sshd", "/usr/bin/sshd") if os.path.exists(p)), None)


@pytest.fixture
def ssh_rig(tmp_path, settings, org):
    """A running organizer on a Unix socket, the gate wrapper, a Spark sshd and a relay sshd."""
    if sshd_binary() is None or shutil.which("ssh") is None or shutil.which("ssh-keygen") is None:
        pytest.skip("OpenSSH (sshd, ssh, ssh-keygen) is not installed")
    import tempfile

    import uvicorn

    root = Path(tempfile.mkdtemp(prefix="zi"))  # short: a Unix socket path has a small length limit
    home = root / "home"
    (home / ".ssh").mkdir(parents=True)
    sock = root / "o.sock"
    app = create_app(settings, organizer=org)
    server = uvicorn.Server(uvicorn.Config(app, uds=str(sock), log_level="warning", lifespan="on"))
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()
    for _ in range(200):
        if server.started:
            break
        time.sleep(0.02)
    # the forced command: an instance wrapper like the deployed one, with HOME pointed away from the real one
    gate = root / "zhiji-inbox"
    gate.write_text("#!/bin/sh\n"
                    f"export HOME='{home}' ORGANIZER_VENV='{sys.prefix}' ORGANIZER_DATA_DIR='{settings.data_dir}'"
                    f" ORGANIZER_UDS='{sock}' ZHIJI_INBOX_GATE='{gate}'\n"
                    f"exec '{SPARK / 'zhiji-inbox'}' \"$@\"\n")
    gate.chmod(0o755)
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "phone", "-f", str(root / "phone")], check=True)
    spark_ak, relay_home = root / "spark_ak", root / "relay_home"
    relay_home.mkdir()
    rig = {"root": root, "home": home, "gate": gate, "settings": settings, "org": org, "spark_ak": spark_ak,
           "relay_home": relay_home, "phone_pub": (root / "phone.pub").read_text().strip()}
    rig["spark"] = SSHD(root, "spark", spark_ak)
    rig["relay"] = SSHD(root, "relay", relay_home / ".ssh" / "authorized_keys")
    (root / "known_hosts").write_text(rig["spark"].known_hosts_line() + rig["relay"].known_hosts_line())
    yield rig
    rig["spark"].stop()
    rig["relay"].stop()
    server.should_exit = True
    thread.join(timeout=10)
    shutil.rmtree(root, ignore_errors=True)


def ssh(rig, port: int, *args: str, stdin: bytes = b"", timeout: float = 60, extra: tuple = ()):
    """The phone's side, played by OpenSSH: only the phone key, only pinned host keys, no user config."""
    base = ["ssh", "-F", "/dev/null", "-o", "BatchMode=yes", "-o", "IdentitiesOnly=yes", "-o", "IdentityAgent=none",
            "-o", f"UserKnownHostsFile={rig['root'] / 'known_hosts'}", "-o", "GlobalKnownHostsFile=/dev/null",
            "-o", "StrictHostKeyChecking=yes", "-o", "LogLevel=ERROR", "-i", str(rig["root"] / "phone"),
            "-p", str(port), *extra, f"{getpass.getuser()}@127.0.0.1", *args]
    try:
        return subprocess.run(base, input=stdin, capture_output=True, timeout=timeout)
    except subprocess.TimeoutExpired as exc:
        return subprocess.CompletedProcess(base, "timeout", exc.stdout or b"", exc.stderr or b"")


def test_sshd_holds_the_phone_key_to_the_gate(ssh_rig):
    rig = ssh_rig
    out = phone_keys.authorize("sim1", rig["phone_pub"], path=rig["spark_ak"], gate_path=str(rig["gate"]))
    assert out["changed"] is True
    port = rig["spark"].port
    # the largest sealed entry, through sshd's forced command, on stdin
    biggest = wire_of(sealed.MAX_SEALED_BYTES, b"\x33")
    r = ssh(rig, port, f"zhiji-inbox add --sealed --id {V_ID} --json", stdin=biggest.encode(), timeout=120)
    assert r.returncode == 0, r.stderr
    assert phone_reply(r.stdout.decode()) == {"ok": True, "id": V_ID, "inbox_id": V_ID, "duplicate": False}
    assert rig["org"].inbox.one(V_ID)["blob"] == biggest
    r = ssh(rig, port, f"zhiji-inbox add --sealed --id {V_ID} --json", stdin=biggest.encode(), timeout=120)
    assert phone_reply(r.stdout.decode())["duplicate"] is True
    r = ssh(rig, port, "zhiji-inbox status")
    assert r.returncode == 0 and "1 条" in r.stdout.decode()
    # anything else is refused by the gate: other commands, the admin commands, a shell
    for cmd in ("cat /etc/hosts", f"zhiji-inbox authorize-phone --key-id x --pubkey '{rig['phone_pub']}' --json",
                "zhiji-inbox list-phones --json", "zhiji-inbox revoke-phone --key-id sim1 --json", "sh -i", ""):
        r = ssh(rig, port, *([cmd] if cmd else []))
        assert r.returncode == 1, (cmd, r.stdout, r.stderr)
    assert not (rig["home"] / ".ssh" / "authorized_keys").exists()
    assert phone_keys.list_phones(path=rig["spark_ak"])["phones"][0]["key_id"] == "sim1"
    # restrict: no port forwarding from the Spark
    r = ssh(rig, port, timeout=10, extra=("-W", f"127.0.0.1:{port}"))
    assert r.returncode != 0
    # revoked: the key no longer gets in at all
    phone_keys.revoke("sim1", path=rig["spark_ak"])
    r = ssh(rig, port, "zhiji-inbox status")
    assert r.returncode == 255 and b"denied" in r.stderr.lower()


def test_sshd_holds_the_phone_key_on_the_relay_to_one_tunnel(ssh_rig):
    rig = ssh_rig
    spark_port, relay_port = rig["spark"].port, rig["relay"].port
    phone_keys.authorize("sim1", rig["phone_pub"], path=rig["spark_ak"], gate_path=str(rig["gate"]))
    ktype, b64 = rig["phone_pub"].split()[:2]
    rc, out, err = relay(rig["relay_home"], "add", "sim1", "127.0.0.1", str(spark_port), ktype, b64)
    assert rc == 0 and out["changed"] is True, err
    # phone -> relay (tunnel) -> Spark gate, the way the phone app connects
    jump = ("-o", "ProxyCommand=" + " ".join([
        "ssh", "-F", "/dev/null", "-o", "BatchMode=yes", "-o", "IdentitiesOnly=yes", "-o", "IdentityAgent=none",
        "-o", f"UserKnownHostsFile={rig['root'] / 'known_hosts'}", "-o", "StrictHostKeyChecking=yes",
        "-o", "LogLevel=ERROR", "-i", str(rig["root"] / "phone"), "-p", str(relay_port), "-W", "%h:%p",
        f"{getpass.getuser()}@127.0.0.1"]))
    r = ssh(rig, spark_port, f"zhiji-inbox add --sealed --id {V_ID} --json", stdin=V_WIRE.encode(), extra=jump)
    assert r.returncode == 0, r.stderr
    assert phone_reply(r.stdout.decode())["ok"] is True
    # on the relay the key can do nothing else: no command, no other tunnel target, no listening port
    r = ssh(rig, relay_port, "echo RAN-ON-RELAY")
    assert b"RAN-ON-RELAY" not in r.stdout and r.returncode != 0
    r = ssh(rig, relay_port, timeout=10, extra=("-W", f"127.0.0.1:{relay_port}"))
    assert r.returncode != 0
    r = ssh(rig, relay_port, timeout=5, extra=("-N", "-o", "ExitOnForwardFailure=yes", "-R", "127.0.0.1:0:127.0.0.1:9"))
    assert r.returncode not in (0, "timeout"), r.stderr
    # unpairing on the relay closes the tunnel
    rc, out, _ = relay(rig["relay_home"], "remove", "sim1")
    assert rc == 0 and out["removed"] == 1
    r = ssh(rig, spark_port, "zhiji-inbox status", extra=jump)
    assert r.returncode != 0
