import AppKit
import BestASRDomain
import Foundation
import UniformTypeIdentifiers

/// One thing the user handed to bestASR, before any file is copied. Content
/// is always information to keep, never an instruction to follow.
public enum IntakeCandidate: Equatable, Sendable {
  /// Text already converted to plain text on this Mac.
  case text(String, extractor: String)
  /// Image bytes from the pasteboard (a screenshot, a copied image).
  case imageData(Data, typeIdentifier: String)
  /// PDF bytes from the pasteboard.
  case pdfData(Data)
  /// A file the user pasted or dropped; classified and read later.
  case file(URL)
}

/// Pasteboard types that say what a copy is, not what it contains.
public enum IntakePasteboardMarks {
  /// Written by bestASR next to its own copies (an uninserted dictation, a
  /// 指令 answer, a history copy, "复制这件事"), so ⌘V in bestASR does not take
  /// them in again as a new item labelled with some other App.
  public static let ownOrigin = NSPasteboard.PasteboardType("com.bestasr.origin")
  /// nspasteboard.org markers: password managers mark passwords and one-time
  /// codes concealed/transient; auto-generated content was not copied by
  /// the user. None of these is ever kept.
  public static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
  public static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
  public static let autoGenerated = NSPasteboard.PasteboardType(
    "org.nspasteboard.AutoGeneratedType")

  public static let privateMessage = "剪贴板内容被标记为隐私或临时，未收进来"
  public static let ownMessage = "这是织机自己复制的内容，未重复收进来"

  /// Why these pasteboard types must not be taken in, if they must not.
  public static func refusal(types: [NSPasteboard.PasteboardType]) -> String? {
    if types.contains(where: { [concealed, transient, autoGenerated].contains($0) }) {
      return privateMessage
    }
    if types.contains(ownOrigin) { return ownMessage }
    return nil
  }

  /// bestASR's own text copy: the text plus the origin mark, one item.
  @MainActor
  @discardableResult
  public static func writeOwnText(_ text: String, to pasteboard: NSPasteboard) -> Bool {
    pasteboard.clearContents()
    let item = NSPasteboardItem()
    guard item.setString(text, forType: .string),
      item.setData(Data(), forType: ownOrigin)
    else { return false }
    return pasteboard.writeObjects([item])
  }
}

/// The representations one pasteboard item or one dragged item offers, and
/// the single rule for which one becomes the candidate. Paste and drop both
/// use it, so they cannot drift apart.
///
/// Order: plain text (unless it is only a link next to an image), then
/// PNG/TIFF/JPEG/HEIC image data, PDF, RTF, and HTML. Text wins over the image
/// or PDF rendering that editors (Word, Pages) add to copied text.
public struct IntakeRepresentations: Equatable, Sendable {
  public var plainText: String?
  public var image: (data: Data, typeIdentifier: String)?
  public var pdf: Data?
  public var rtf: Data?
  public var html: Data?

  public init(
    plainText: String? = nil, image: (data: Data, typeIdentifier: String)? = nil,
    pdf: Data? = nil, rtf: Data? = nil, html: Data? = nil
  ) {
    self.plainText = plainText
    self.image = image
    self.pdf = pdf
    self.rtf = rtf
    self.html = html
  }

  public static func == (lhs: Self, rhs: Self) -> Bool {
    lhs.plainText == rhs.plainText && lhs.image?.data == rhs.image?.data
      && lhs.image?.typeIdentifier == rhs.image?.typeIdentifier && lhs.pdf == rhs.pdf
      && lhs.rtf == rhs.rtf && lhs.html == rhs.html
  }

  /// Image types in preference order.
  public static let imageTypeIdentifiers: [String] = [
    UTType.png.identifier, UTType.tiff.identifier, UTType.jpeg.identifier,
    UTType.heic.identifier,
  ]

  /// `origin` names the extractor family, e.g. `pasteboard` or `drop`.
  public func candidate(origin: String) -> IntakeCandidate? {
    let plain = plainText.map(IntakeTextExtractor.sanitized)
    let image = image.flatMap { $0.data.isEmpty ? nil : $0 }
    // A copied image may carry its URL as text, which is not the content.
    if let plain, !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
      image == nil || !Self.isLoneLink(plain)
    {
      return .text(plain, extractor: "\(origin)-text-v1")
    }
    if let image { return .imageData(image.data, typeIdentifier: image.typeIdentifier) }
    if let pdf, !pdf.isEmpty { return .pdfData(pdf) }
    if let rtf, let text = IntakeTextExtractor.rtfText(rtf), !text.isEmpty {
      return .text(text, extractor: "\(origin)-rtf-v1")
    }
    if let html, let text = IntakeTextExtractor.htmlText(html), !text.isEmpty {
      return .text(text, extractor: "\(origin)-html-xml-v1")
    }
    return nil
  }

  public static func isLoneLink(_ text: String) -> Bool {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed) else {
      return false
    }
    return url.scheme != nil
  }
}

/// Reads the pasteboard the user explicitly pasted into bestASR. Tests pass a
/// private named pasteboard; the App passes the general pasteboard only for a
/// user-initiated paste or the "收进来" command.
///
/// Preference: file URLs; then per pasteboard item the `IntakeRepresentations`
/// order. HTML is converted with `XMLDocument` (never the WebKit-backed
/// attributed-string importer, which can fetch remote resources), dropping
/// scripts and styles. A pasteboard marked concealed/transient/auto-generated
/// (password managers) or written by bestASR itself is refused whole.
@MainActor
public struct IntakePasteboardReader {
  public enum Reading: Equatable, Sendable {
    case candidates([IntakeCandidate])
    case refused(String)
  }

  private let pasteboard: NSPasteboard

  public init(pasteboard: NSPasteboard) {
    self.pasteboard = pasteboard
  }

  /// Types a paste or a drop can offer; also used as the drop type list.
  public static let acceptedTypeIdentifiers: [String] = [
    UTType.fileURL.identifier, UTType.png.identifier, UTType.tiff.identifier,
    UTType.jpeg.identifier, UTType.heic.identifier, UTType.pdf.identifier,
    UTType.utf8PlainText.identifier, UTType.plainText.identifier,
    UTType.rtf.identifier, UTType.html.identifier,
  ]

  public func read() -> Reading {
    var types = pasteboard.types ?? []
    for item in pasteboard.pasteboardItems ?? [] { types.append(contentsOf: item.types) }
    if let refusal = IntakePasteboardMarks.refusal(types: types) { return .refused(refusal) }
    let files =
      (pasteboard.readObjects(
        forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]
      ) as? [URL]) ?? []
    if !files.isEmpty { return .candidates(files.filter(\.isFileURL).map(IntakeCandidate.file)) }
    var result: [IntakeCandidate] = []
    for item in pasteboard.pasteboardItems ?? [] {
      // Refused before sanitizing: a huge pasted log is not copied around.
      if let string = item.string(forType: .string),
        IntakeProcessor.exceedsTextLimit(string)
      {
        return .refused(IntakeProcessor.tooMuchTextMessage)
      }
      if let candidate = Self.representations(of: item).candidate(origin: "pasteboard") {
        result.append(candidate)
      }
    }
    return .candidates(result)
  }

  private static func representations(of item: NSPasteboardItem) -> IntakeRepresentations {
    let image = IntakeRepresentations.imageTypeIdentifiers.lazy.compactMap {
      identifier -> (data: Data, typeIdentifier: String)? in
      guard let data = item.data(forType: NSPasteboard.PasteboardType(identifier)),
        !data.isEmpty
      else { return nil }
      return (data, identifier)
    }.first
    return IntakeRepresentations(
      plainText: item.string(forType: .string), image: image,
      pdf: item.data(forType: .pdf), rtf: item.data(forType: .rtf),
      html: item.data(forType: .html)
    )
  }
}
